# Generated by Django 4.1.7 on 2023-10-04 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
