# Generated by Django 4.1.7 on 2023-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingsystem', '0002_alter_parrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrequest',
            name='department',
            field=models.CharField(choices=[('Vender department', 'Vender department'), ('Tender department', 'Tender department'), ('Financial department', 'Financial department')], max_length=50),
        ),
    ]
