# Generated by Django 4.1.7 on 2023-10-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingsystem', '0003_alter_parrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrequest',
            name='category',
            field=models.CharField(choices=[('s', 'Safety stock'), ('p', 'Pipeline Stock'), ('a', 'Anticipatory Stock'), ('d', 'Decoupling Stock')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('expired', 'expired')], max_length=50),
        ),
    ]
