# Generated by Django 4.2 on 2023-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingsystem', '0004_alter_parrequest_category_alter_parrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrequest',
            name='was_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parrequest',
            name='was_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parrequest',
            name='was_pending',
            field=models.BooleanField(default=True),
        ),
    ]
