# Generated by Django 4.1.7 on 2024-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trackingsystem",
            "0005_parrequest_was_approved_parrequest_was_expired_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("expired", "expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
