# Generated by Django 4.1.7 on 2024-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackingsystem", "0006_alter_parrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("expired", "expired"),
                ],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
