# Generated by Django 4.1.7 on 2024-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackingsystem", "0007_alter_parrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parrequest",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="par_requests/"),
        ),
    ]
