# Generated by Django 5.0.3 on 2024-07-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackingsystem", "0008_parrequest_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="parrequest",
            name="signed_attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="signed_par_requests/"
            ),
        ),
    ]
